### ISSUE TITLE
IOException on saving votepoints

### ISSUE THREAD

**Issue by kory33** [kory33/SignVote#14]
The plugin often fails to save votepoints,
giving out IOException

**Comment by kory33** [comment]
Nope.
```[20:35:38 WARN]: java.nio.file.AccessDeniedException: plugins\SignVote\sessions\session\votepoints\abdsioahds.json
[20:35:38 WARN]:        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
[20:35:38 WARN]:        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[20:35:38 WARN]:        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[20:35:38 WARN]:        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
[20:35:38 WARN]:        at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
[20:35:38 WARN]:        at java.nio.file.Files.newOutputStream(Unknown Source)
[20:35:38 WARN]:        at com.github.kory33.signvote.utils.FileUtils.writeJSON(FileUtils.java:49)
[20:35:38 WARN]:        at com.github.kory33.signvote.session.VoteSession.lambda$2(VoteSession.java:158)
[20:35:38 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[20:35:38 WARN]:        at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
[20:35:38 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[20:35:38 WARN]:        at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
[20:35:38 WARN]:        at java.util.concurrent.CountedCompleter.exec(Unknown Source)
[20:35:38 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[20:35:38 WARN]:        at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
[20:35:38 WARN]:        at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
[20:35:38 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
[20:35:38 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
[20:35:38 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[20:35:38 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[20:35:38 WARN]:        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
[20:35:38 WARN]:        at com.github.kory33.signvote.session.VoteSession.saveTo(VoteSession.java:156)
[20:35:38 WARN]:        at com.github.kory33.signvote.manager.VoteSessionManager.saveSession(VoteSessionManager.java:68)```

**Comment by kory33** [comment]
Seems like this issue gets reproduced on v0.2.3 as well.
Any additional information or a step for reproduction is welcomed.

**Comment by kory33** [comment]
`ddf1f5e79483198739e54e0cd8725ee86d5e506c`
may have fixed the issue

**Comment by kory33** [comment]
Most probably the issue has been resolved. Closing for now.
